### ISSUE TITLE
How does marshalling data to and from gluon work? 

### ISSUE THREAD

**Issue by blt** [gluon-lang/gluon#201]
Hi folks!

I've been evaluating gluon and have a documentation question. In the features list there's this promise:

> Simple embedding - Marshalling values to and from gluon requires next to no boiler plate allowing functions defined in Rust to be directly passed to gluon.

That sounds great! I've read the [embedding API](https://github.com/gluon-lang/gluon/blob/master/TUTORIAL.md#embedding-api) materials, have read through the API docs and have been poking around in the test code in this repository but can't figure out how you _do_ this. In particular, I want to define a struct in rust, pass it to a function in gluon for modification and then continue on with my modified struct. I sort of see how part of that's done with with example:

```rust
fn factorial(x: i32) -> i32 {
    if x <= 1 { 1 } else { x * factorial(x - 1) }
}
let vm = new_vm();
vm.define_global("factorial", factorial as fn (_) -> _)
    .unwrap();
let (result, _) = Compiler::new()
    .run_expr::<i32>(&vm, "example", "factorial 5")
    .unwrap();
assert_eq!(result, 120);
```

in that `.run_expr::<i32>(&vm, "example", "factorial 5")` shows how a function with an argument gets called but if I wanted to pass a more complicated structure through like

```rust
struct Point {
  x: i64,
  y: i64,
  meta: HashMap<String, String>,
}
```

then I'm left at a loss. If I wanted to create a `Point` in rust and then pass that to a gluon function which would double both `x` and `y` and then add a pair `"gluon": "very useful!"` to the `Point`, how would I do that? 

Thanks!

**Comment by Marwes** [comment]
Looks like I have forgotten to add an example on how to marshal custom data types! Perhaps the best example on what you want to do is currently how rustyline is embedded https://github.com/gluon-lang/gluon/blob/7c517cad1d6c467048bd0a05a9bffc607adc6e15/src/repl.rs#L124-L182. Of not is that `Userdata`, `VmType` and `Debug` needs to be implemented for the type and you need to ensure that the type you want to embed is also registered before adding any functions or data that refers to the type. You may also notice that `Mutex` is needed. As all objects are shared we need interior mutability to preserve safety and as gluon also allows threads to execute in parallel we also require `Send+ Sync`.

In the future I hope to add some way relax the `Send + Sync` bound in some cases so that `RefCell` and `Cell` can be used which have less overhead but currently `Send + Sync` is required.

**Comment by blt** [comment]
That's a big help! Okay, I think I understand how to do part of what I was hoping to do. The other half, how do I pass data down into gluon so that it can modify it? In the example above it looks like rust does all the setup and then hands control off to gluon, no?

**Comment by Marwes** [comment]
Yup, gluon takes ownership of the value. Not really sure what you mean. Do you want to share ownership of the value between gluon and rust? The easiest way is currently to wrap your value in an `Arc` and use that in Rust. It is possible to use [Root](https://docs.rs/gluon_vm/0.2.2/gluon_vm/thread/struct.Root.html) as a reference counted pointer as well but it is not as user friendly and documented as it could be at the moment.

**Comment by blt** [comment]
Got it. What I'm building is effectively a router and I'd like to add user-extendable manipulation of in-flight data. I'm imagining that will look like this:  

* rust builds a data-structure -> 
* gluon function is called on that structure -> 
* rust uses modified (or newly alloc'ed) structure

I don't expect there to be long-running gluon in this setup, just a bunch of functions strung together.

**Comment by Marwes** [comment]
That sounds like something that gluon should do well but I am not sure how to best handle it at the moment.

Essentially this is just a pure function `MyData -> MyData`. The problem comes in how to represent the data, while using userdata (rust structures) should be as close as possible in usability as records and variants defined in gluon they aren't quite there yet. So probably, at least currently, marshaling into gluon records may be more usable.

On the other hand mutating the structure as in your original example might just be a bit more flexible at the moment, especially if you want a `HashMap` as there is no support for marshaling gluons `Map` type at the moment.

**Comment by Marwes** [comment]
I should say that how to represent shared data is a though problem and the best solution is likely to vary between applications. I remember having this problem when writing a game which embedded Lua as well. Having the value owned by lua makes it problematic to reason about ownership and how to use it outside Lua and owning the object in native code makes the lua code more complicated :/.

**Comment by blt** [comment]
Indeed! 

Okay, let me flesh out my ambitions a touch. I want to write a function in gluon that takes some struct `MyData` and a vec of routes which does some computation and returns a vec of tuples of route and `MyData` vecs. Or, 

    type Route = String
    fn process(data: MyData, routes: [Route]) -> [(Route, [MyData])]

Like you say, the problematic thing here is the–potential–creation of new `MyData` structs in gluon and passing the ownership back to Rust. Ultimately, Rust has to own everything. The `MyData` structs that get passed back up to Rust may be non-altered clones of the original `MyData` or they might be substantially modified.

**Comment by Marwes** [comment]
Is there a question in there? :)

**Comment by blt** [comment]
Hah, no, in retrospect there isn't a question there. I'll poke around with the information you've shared and see if I can't come up with something more concrete. 

Thanks for you help @Marwes!

**Comment by brendanzab** [comment]
Will be awesome to hear more from your experiences @blt! We have a gitter room at https://gitter.im/gluon-lang/gluon if you want to chat :)

**Comment by Marwes** [comment]
We could do with some more examples on the embedding part so please let me know if you get something working or not and I may be able to turn it into an example!

**Comment by blt** [comment]
Hi @Marwes, I kinda trailed off there because I was time-boxed on a private project. Unfortunately I did not end up understanding how to use gluon in the way that I needed and resorted to the use of Lua. The project that this question motivated is now open-source: https://github.com/postmates/cernan

In particular, what I'm doing is providing users with a 'filter' functionality, documented here: https://github.com/postmates/cernan/wiki/Filters These filters receive a reference payload structure, fiddle with it and return, leaving Rust to use the fiddled with payload. The actual implementation is here: https://github.com/postmates/cernan/blob/master/src/filter/programmable_filter.rs

I'd still really like to use gluon inside cernan and if you have any suggestions or documented examples I'd be grateful. Thanks!

**Comment by Marwes** [comment]
@blt #226 should be a pretty good explanation fairly soon. I haven't gotten to explaining it properly yet as I got sidetracked rewriting it to be asynchronous but I can give you a ping once that is done as I don't see anything in your link which can't be implemented with gluon.

**Comment by Marwes** [comment]
@blt I have tried to explain as much as possible in #226. The example is not as straightforward as I'd like since it involves asynchronous actions in addition to the basic userdata handling so I may do simpler example later which solely focuses on marshaling data but hopefully it can be helpful. (Since it relies on unmerged changes in the futures branch there are a lot of changes so just ignore everyting outside of `examples/http`)
