### ISSUE TITLE
Say what tokens are expected in parser error messages

### ISSUE THREAD

**Issue by saifikhan** [gluon-lang/gluon#270]
compiled 'gluon' from the master

i'm getting the following error, while trying to execute any of the examples (beyond hello world and numbers) from the tutorial.

`> let record = { pi = 3.14, add1 = (+) 1.0}
<top>:Line: 1, Column: 1: Unexpected end of file
let record = { pi = 3.14, add1 = (+) 1.0}
^'

Is there a work around ?

**Comment by Marwes** [comment]
Looks like a poor error message. It should say something like expected `in` because it expects all let bindings to be followed by an expression which the `let` expression evaluates to.

https://github.com/gluon-lang/gluon/blob/master/TUTORIAL.md#variable-bindings

That being said, in the repl (but not in normal files) I want your example to work as a way to bind temporary variables for later use. Need to open an issue for that.

**Comment by Marwes** [comment]
The `UnrecognizedToken` errors here https://github.com/gluon-lang/gluon/blob/195bea377a300be736561940bb9a4e43a86280f2/parser/src/lib.rs#L121-L126 also contain information about what tokens were expected https://github.com/nikomatsakis/lalrpop/pull/178. We should use this information in the error messages as well.
