### ISSUE TITLE
no output on command line

### ISSUE THREAD

**Issue by srctxt** [gluon-lang/gluon#365]
there is no output 👍 

$ cat t.glu 

```
let prelude = import! "std/prelude.glu"
let io = import! "std/io.glu"

let run x : () -> IO () =
    io.println "gluon (:h for help, :q to quit)"
run
```

$ ./target/debug/gluon t.glu

**Comment by Marwes** [comment]
Thanks for reporting! It appears that running files from the command line has regressed so that it no longer runs IO expressions. Fairly simple to fix but I will do some cleanup of the API being used as well.

Note that you actually have a bug in the example  you posted. The `run` function must be called as well or else the `IO` action won't be executed (you only return the function `run` as it is currently).

```f#
let prelude = import! "std/prelude.glu"
let io = import! "std/io.glu"

let run x : () -> IO () =
    io.println "gluon (:h for help, :q to quit)"
run ()
 // ^ here
```
