### ISSUE TITLE
( Question ) Dynamic recompiling

### ISSUE THREAD

**Issue by ShalokShalom** [gluon-lang/gluon#454]
Since Gluon is intended to be embedded and games engines do this in order to provide a scripting interface: Is there any technique/trick to do this in Gluon? Specific use case is Amethyst, the data oriented Rust game engine, which considers Gluon as a possible solution.

**Comment by Marwes** [comment]
Since https://github.com/gluon-lang/gluon/issues/340 was fixed it is now possible to reload any module by just loading it again. Where it gets a bit complicated is that only the specific module being reloaded is what gets changed, any modules *depending* on the reloaded module will still refer to the previous version of the module.

```
# x -> y   "x depends on y"

Module A -> Module B

# Reload B

Module A -> Module B

Module B v2

# Referring to `B` from new scripts will refer to version 2 at this point, but A will still refer to version 1 until it gets reloaded as well.
```

The part of dynamically recompiling the dependency graph like this is not implemented yet, but it is something that the language server will need eventually,

That said, as long the number of scripts is small then it is possible to remove all modules that might be affected (standard modules wouldn't need recompiling and could be left while user scripts are removed) and then all those scripts are reloaded all at once. Which would ensure that no old scripts sticks around.

**Comment by ShalokShalom** [comment]
Oh, this is wonderful, actually :D
