### ISSUE TITLE
Make it possible to test the REPL

### ISSUE THREAD

**Issue by Marwes** [gluon-lang/gluon#51]
As more features gets added to the REPL it would be nice to improve the testing for it. The REPL can however be tricky to test as one needs to be able to send commands to the terminal programmatically. In python I found the [pexpect](https://github.com/pexpect/pexpect) library which seems to be able to do this. It is a bit of a heavy weight solution to take on a python dependency just for some tests though and it would really nice if a library like pexpect could be ported to RUST. I don't have a good estimate to how much work such a port would be but it might be an interesting project to do (which would likely be useful outside of gluon as well)!

**Comment by memoryruins** [comment]
It appears a crate has been worked on recently with that aim - [rexpect](https://github.com/philippkeller/rexpect), and trying it with the gluon repl, and it works! I'll open a PR for some basic tests, mostly based off the tutorial as if a new user was following along. More tests needed, and currently, boilerplate could be cut down.

**Comment by memoryruins** [comment]
One issue, which may be a combination of a more general REPL issue, is if a test fails, the error is a bit of a mess due to unwrapping the error-chain struct. It was especially so when testing the ``:i`` names example in the readme.
```
repl.send_line(":i std.prelude.List").unwrap();
repl.exp_string("type std.prelude.List a = | Nil | Cons a (std.prelude.List a)").unwrap();
```
which fails while manually using the repl as well. It outputs the entire source of the prelude in the repl + the error ``does not have the field `List``.  Wrap that in the error-chain struct then ``.unwrap()`` it -- it isn't pretty. Similarly, when manually creating a function in the repl with ``let f x = x + 1``, the repl outputs the entire expansion in return, which I was unsure if expected behavior (instead of returning something like ``Int -> Int``), so there are not tests included for that as well.

**Comment by Marwes** [comment]
The error messages you see should be filtered down a bit it just haven't been implemented for https://github.com/gluon-lang/gluon/blob/d7ce3e81c1fcfdf25cdd6d1abde2b6e376b4bf50/vm/src/lib.rs#L120-L122 (unification errors gets filtering applied here https://github.com/gluon-lang/gluon/blob/d7ce3e81c1fcfdf25cdd6d1abde2b6e376b4bf50/check/src/typecheck.rs#L118 though there is rather a lot code ther right now.

**Comment by Marwes** [comment]
> Similarly, when manually creating a function in the repl with let f x = x + 1, the repl outputs the entire expansion in return, which I was unsure if expected behavior (instead of returning something like Int -> Int), so there are not tests included for that as well.

https://github.com/gluon-lang/gluon/issues/467
