### ISSUE TITLE
Async and gluon

### ISSUE THREAD

**Issue by Ekleog** [gluon-lang/gluon#537]
Hello,

So I'm considering using gluon for the configuration of a project I'm currently doing.

## What I want to do

Basically, the gluon code would have to be a function that would have a type like this one (simplified for the sake of demonstration, in Rust:
```rust
fn filter(v: String) -> impl Future<Item = bool, Error = ()>;
```
That is, that takes as an input a `String` and returns whether the `String` matches the filter defined in the gluon code, in a future.

The point is, this `filter` function will likely have to do things like remote calls to LDAP directories, etc. Which would thus better be handled as an async future.

## What is there

If I understand correctly, currently gluon has a `run_expr_async` method that asynchronously runs synchronous code on the VM thread. However, it also has as a consequence that not two expressions can run at the same time on the same VM thread.

So, if I understand correctly, even with `run_expr_async`, only a single connexion to the LDAP directory could happen at once, to keep the previous example. Or only N, if I manage myself a pool of N VM threads. (and I must say I don't look forward to manually managing a pool of VM threads by hand in an async world)

## What could be there

So what I think I want is actually a way to build a `Future` from gluon code. This way, there could be a single VM thread, and then when wanting to run a task it's possible to do something like (pseudo-syntax, I haven't actually started using gluon in actual code yet, and prefer to think ahead of time on how to use it):
```rust
vm.get_function::<Fn(String) -> impl Future<Item = bool, Error = ()>>("filter")
    .call(the_string_to_filter)
    .and_then(|fut| fut)
    .and_then(|res| use_the_filter_result(res))
```

So what I'm looking for is a library for building futures in gluon, and (maybe?) syntax extensions that would allow for easily building futures in gluon. (in the same manner as `async`/`await` are currently being debated on)

I say “(maybe?)” because I'm not sure about the need for a syntax: gluon already has first-class support for monads, and `Future` looks “monad-y” for a non-functional-developer like me. So maybe all that'd be needed would be a gluon library for futures?

Has anyone started thinking about this?

**Comment by Marwes** [comment]
> So I'm considering using gluon for the configuration of a project I'm currently doing.

That sounds like a cool project!

Depending on how much control you need over the futures this should already work. Using the [std.thread](http://gluon-lang.org/doc/nightly/std/thread.html) module it is possible to create new threads from inside gluon and dispatch functions on them. These threads should be cheap enough to create and use just once though I do want a way to reuse them eventually.

The interface to interact with running threads is rather limited at the moment though so I'd really appreciate suggestions for improvements here!

So something like this should do what you want I think (though I haven't tested it).

```f#
let { new_thread, spawn_on } = import! std.thread

let async f : (() -> IO a) -> IO (IO a) =
    do thread = new_thread ()
    spawn_on thread f

// Dispatch two asynchronous request
do action1 = async (\_ -> filter "abc")
do action2 = async (\_ -> filter "123")
// Then wait for them, each action will run concurrently on the event loop
do result_1 = action1
do result_2 = action2
// Do something here with `result_1` and `result_2`
```

**Comment by Ekleog** [comment]
I'll make sure to let you know more about this project when it's closer to completion, as it's open source, but would rather avoid premature optimism :)

So if I understand correctly, `std.thread` is a green threading library? If so, I wonder whether it'd be possible to make it interwork with futures. With the LDAP example, what I was thinking of is:
1. Bind functions from the [ldap3](https://crates.io/crates/ldap3) crate into gluon
2. Have the gluon script combine together the futures returned by these functions
3. Run the combined future on the tokio event loop

With the `std.thread` solution, I'm a bit worried this would require quite a lot of glue to have ldap3 functions running on the gluon (pun not intended) event loop, likely some busy-waiting, and even maybe not possible because ldap3 appears to require being run on a tokio event loop (well, maybe possible by having a separate tokio event loop and message-passing between main-tokio, gluon and ldap3-event-loop-tokio, but then the architecture becomes… complex).

Which is the reason why I was thinking of using gluon as a “runtime future combinator.” Does this reasoning make sense at all? I'm not familiar at all with gluon concepts (for the time being :)).

**Comment by Marwes** [comment]
> So if I understand correctly, std.thread is a green threading library?

Yes, though it is entirely built on top of `futures` + `tokio` (once everything stabilizes I can probably get away with only `futures` though). Thus there is no gluon event loop, if you return a future from a Rust function bound to gluon, the gluon (green) thread will poll the future and if it returns `Async::NotReady` then that status will bubble up through the future returned by `run_expr_async`.

`spawn_on` on the other hand will `spawn` the future on tokio's event loop and return a oneshot future which can be polled later which is why it returns `IO (IO a)`, the first `IO` spawns the future so it runs concurrently and it is only when the inner `IO` gets run that the gluon scripts "waits" (by polling the oneshot receiver) for the action to actually complete.

So as long as you just want to dispatch a number of different futures and [join](https://docs.rs/futures/0.2.1/futures/trait.FutureExt.html#method.join) on their results then it will work with the example above. Other async combinators such as [select](https://docs.rs/futures/0.2.1/futures/trait.FutureExt.html#method.select) could be added as well though they don't exist at the moment.

**Comment by Ekleog** [comment]
Oh, thanks! I think I now understand things a bit better: the thing I completely missed was that `RootedThread` was not actually a thread, I assumed it spawned an OS thread, and `run_expr` / `run_expr_async` were two ways of interacting with this thread! Having seen https://docs.rs/gluon/*/src/gluon/lib.rs.html#416-426 I now (think I) understand that `Thread` is actually just a future.

So, just to sum up and check I've correctly understood the gluon architecture around async now, I should, for the abovementioned example (code just for giving an idea, not trying to be exact):
1. Build a compiler pipeline with `new_vm`
2. Add in the ldap3 functions with `add_extern_module` (which will require wrapping them in functions returning `FutureResult<TheLdap3FutureType>`)
3. Fill the VM with the user-defined configuration file with
    ```rust
    Compiler::new().run_expr(&vm, "config", r#" import! "/etc/my-config.glu" "#).unwrap()
    ```
4. Before the tokio event loop, check the configuration has the right type with
    ```rust
    let _: FunctionRef<fn(String) -> bool> = vm.get_global("filter").unwrap()
    ```
5. Once inside my tokio event loop, recover a future that'll implicitly be paused when ldap3 call functions do so with
    ```rust
    vm.get_global("filter").unwrap().call_async("my string to filter")
    ```

And this will implicitly run each `call_async` in “parallel”, without requiring use of `std.thread` so long as the gluon code itself doesn't attempt to perform multiple simultaneous async-able actions at once.

Did I understand correctly? This looks great and way better than what I had in mind!

**Comment by Marwes** [comment]
That sounds correct. Is the config file the one defining the `filter` function? Or does that come from `add_extern_module`? You will need to adjust the `get_global(..)` call to retrieve the function so that if it comes from `etc/my-config.glu` then it would be `get_global("etc.my-config.filter)`, or if  it is under `add_extern_module` you will need to prefix it by whatever module name you give that module.

Second, if you want to run multiple things in concurrently by calling from rust you must do the same thing as the script does and allocate one thread for each future you want to run (the`Thread` gets associated with the future returned by `call_async/run_expr_async` so you can't start on another future until the first has returned).

```rust
vm.new_thread().get_global("filter").unwrap().call_async("my string to filter")
```

**Comment by Ekleog** [comment]
My plan is currently to have the `/etc/my-config.glu` file define `let filter str = ...`, as it would define quite a few callbacks :)

About the path issue, I'm not completely sure how to do things yet (questions of path, etc.), but that's unrelated to async so I'll just ask my questions on gitter :)

And thanks for the precisions about the `Thread` becoming associated with the future, as well as for all your explanations before that! :100:
