### ISSUE TITLE
Documentation is not available

### ISSUE THREAD

**Issue by superriva** [gluon-lang/gluon#644]
Documentation for embedding is not available

`https://docs.rs/gluon/*/gluon/fn.new_vm.html`
`The requested resource does not exist`

Need your help, please.

**Comment by Marwes** [comment]
Yeah, this is an issue of docs.rs not being updated. I have thought about uploading docs to gluon-lang.org instead but I don't really want to update all links to it only to then change them back once docs.rs is updated (I rather have the docs there since it allows one to looks at older versions etc).

For the moment the easiest way would be to do `git clone https://github.com/gluon-lang/gluon && cd gluon && cargo doc --open` to get the docs locally at least. I may try and host them anyway on gluon-lang.org though, just not as the canonical docs.

**Comment by Marwes** [comment]
https://internals.rust-lang.org/t/whats-the-state-of-docs-rs/8535

**Comment by Marwes** [comment]
Seems like things are happening on the docs.rs end and the docs for gluon 0.9.4 can at least for the moment be found at http://docsrs.csail.mit.edu/gluon/0.9.4/gluon/.

I also host docs on https://gluon-lang.org/rust_doc/gluon/index.html now (linked from the root page) but I will probably link to docs.rs once that gets sorted out and only have those docs as a mirror.

https://github.com/onur/docs.rs/issues/233
https://github.com/onur/docs.rs/pull/243

**Comment by superriva** [comment]
Glad to see your information. Thank you.

**Comment by QuietMisdreavus** [comment]
The linked PR on docs.rs has been merged and the docs for gluon have been rebuilt: https://docs.rs/gluon/0.9.4/gluon/

**Comment by Marwes** [comment]
🎉 Awesome! Thanks for getting docs.rs updated!
