### ISSUE TITLE
Nature of the VM

### ISSUE THREAD

**Issue by ShalokShalom** [gluon-lang/gluon#734]
Hi there. :D 

Which kind of VM is that one of Gluon? Stack based? 
And which kind of threads does it use?

Thanks :hugs:

**Comment by Marwes** [comment]
Yes, it is a stack based VM with green threads which, since they are threads safe, be ran on different OS threads. The only really special thing about it is that objects have limited form of sharing between each green thread which avoids copying in many cases while also avoid full heap scans https://github.com/gluon-lang/gluon/blob/b7309dcb483c16c963cae2b50106d671ed85c5c8/vm/src/gc.rs#L161-L179

**Comment by ShalokShalom** [comment]
Thanks a lot. You can put this in the documentation, if you think that is fine. Nice day :D
