### ISSUE TITLE
Add a flag to gluon.exe to ignore its internal library modules

### ISSUE THREAD

**Issue by Etherian** [gluon-lang/gluon#751]
It can be difficult to test changes to the standard library using the standalone interpreter / REPL because it finds the modules in its internal standard library before checking the file system for the updated files.

Adding a command line flag to skip its internal modules, or maybe just check the filesystem first, would be a nice convenience.

---

This might be a good introduction for me to Gluon's Rust codebase, if someone could point me to where and what needs to be changed.

**Comment by Marwes** [comment]
Allowing custom modules to shadow standard modules seems like a potential security issue so some care should be taken.

So far I think there are two approaches (that would also work for other use cases).

Add a no-std option which disables loading of the standard library entirely. Since you could still copy over the library files and modify them you could then test those on their own.

Add a special marker to GLUON_PATH which indicates loading the internal standard library and then support multiple paths/markers for that setting. This would let you either remove or reorder the standard library loading to make sure your files come first. This could be used to only copy over a subset of the standard library which then shadows the real files.

I can write up some instructions later, do you have any opinion on which way would be best here? (Or an entirely different solution)

**Comment by Etherian** [comment]
The GLUON_PATH option sounds like it might be more generally useful, but could still be a security vulnerability if the user isn't careful with their GLUON_PATH.

I think the best choice for now is a --no-std command line option. It's simple, and I think it's obvious and deliberate enough to not be a security issue.

I'd love instructions whenever you get a chance.

**Comment by Marwes** [comment]
So the std lib lookup is here https://github.com/gluon-lang/gluon/blob/7b44c202ef17f2974e18d0b5998ac847f684b652/src/import.rs#L183 and you want to thread it in from here https://github.com/gluon-lang/gluon/blob/7b44c202ef17f2974e18d0b5998ac847f684b652/repl/src/main.rs#L106.

You would need to thread that setting into gluon_repl, gluon_doc, gluon_fmt and make sure that it is set on the `Settings` object https://github.com/gluon-lang/gluon/tree/7b44c202ef17f2974e18d0b5998ac847f684b652/src#L246 .

In `import.rs` you can then pass `Compiler` to https://github.com/gluon-lang/gluon/blob/7b44c202ef17f2974e18d0b5998ac847f684b652/src/import.rs#L172-L177 and read the setting there.

Let me know if anything is unclear!

**Comment by Etherian** [comment]
Thanks! I'll let you know if I have any questions.

**Comment by Etherian** [comment]
I noticed file paths passed to `gluon.exe` on the command line are also checked against its internal library. Is this expected behavior?

**Comment by Marwes** [comment]
That's just a consequence of it going through the same loading as any other file (which seems to make sense to me?)

**Comment by Etherian** [comment]
I did find it surprising, but I doubt it would affect many users. I do think it's likely, however, that eventually some file loading behavior will need to differ from script imports in some way. Is there currently a means of achieving that?
