### ISSUE TITLE
Hide Semigroup, Monoid, and Group instances for numbers

### ISSUE THREAD

**Issue by lePerdu** [gluon-lang/gluon#783]
Trying to use `<>`, `empty`, etc. with numbers (`byte`, `int`, and `float`) results in this error: `Unable to resolve implicit. Multiple candidates were found` because there exist both `additive` and `multiplicative` instances. I'm assuming something like #47 would help this sort of problem, but in the meantime, having those instances searched is useless.

One way to "fix" this now is to just not import any of them by default; then whichever one is needed can be imported in however narrow a scope it is needed in (and it will be implicitly be resolved). Doing so would require either moving the definitions to separate modules, or not searching instances that are "nested" inside records as the additive and multiplicative instances are.

**Comment by Marwes** [comment]
This is fixed on master as `?` will only recurse into implicit fields. Since `int.additive/int.multiplicative` is not implicit, they only contain implicit fields `let { ? } = import! std.int` won't import both the instance. Instead  `let { ? } = import! std.int.additive` must be used.

I did however find another related issue which are fixed with #796.
