### ISSUE TITLE
Literature on type system?

### ISSUE THREAD

**Issue by tominated** [gluon-lang/gluon#822]
Hey Gluon folks, I know this isn't really an issue but it seemed like the best place.

I'm attempting to build a programming language with a type system similar to gluon (purely functional, row polymorphic, implicits, effects, etc), and while there's plenty of papers and other resources to refer to, I'm interested to see what Gluon's implementation was informed by.

I'm especially curious as to what kind of algorithm the inference/checking is (it's hard to tell from the code when all the papers are in a more functional style than typical rust). Having types in a record is especially interesting to me as it seems to work like an ocaml module, but I've no idea how that fits in with the row polymorphism & implicit solving.

Again, apologies if this is the wrong place, but I'd love to hear what inspired gluon!

**Comment by Marwes** [comment]
1ML would be the primary inspiration at this point https://people.mpi-sws.org/~rossberg/1ml/ .

For effects https://hackage.haskell.org/package/extensible-effects has been really useful.

Implicits are inspired from OCaml https://www.cl.cam.ac.uk/~jdy22/papers/modular-implicits.pdf though with alterations since records are effectively first class modules (as opposed being separate in OCaml).

http://www.purescript.org/ has been useful as guide to actually implement implicits (the OCaml paper is quite sparse).

There is likely more, certainly for the more "basic" parts of the compiler (unification, parsing, etc) but I have forgotten the sources and internalized most of that at this point.

**Comment by tominated** [comment]
Thanks so much for the references! The 1ML paper looks super interesting and very much the sort of thing i'm looking for
